{% set name = "dmba" %}
{% set version = "0.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dmba-{{ version }}.tar.gz
  sha256: fb89275326e450781c1e7dd7490c7fc01fb5f3e3c4be250729e8b910cf2a1496

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - matplotlib-base
    - pandas
    - scikit-learn
    - python-graphviz

test:
  imports:
    - dmba
    - dmba.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.dataminingbook.com/book/python-edition
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Data Mining for Business Analytics: Concepts, Techniques, and Applications in Python'
  description: |
    Data Mining for Business Analytics: Concepts, Techniques, and 
    Applications in Python (First Edition) Galit Shmueli, Peter C. Bruce, 
    Peter Gedeck, and Nitin R. Patel (c) 2019 John Wiley & Sons, Inc.
  doc_url: https://www.dataminingbook.com/book/python-edition
  dev_url: https://github.com/gedeck/dmba

extra:
  recipe-maintainers:
    - jan-janssen
